### ISSUE TITLE
Instruction clarification needed for Models

### ISSUE THREAD

**Issue by jessicavaughn619** [learn-co-curriculum/python-p4-iam-putting-it-all-together-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/6193/assignments/234473?module_item_id=549401

### Concern

Clarification of instructions - In the lab instructions under Models, the instructions ask you to add VALIDATIONS for the Recipe model, but the Pytests except you to use Check Constraint for the instructions length. It would be helpful in the instructions to be clear that it is asking for a check constraint instead of a validation. I ended up having to continually downgrade my database and then revise it to finally pass this test with check constraint since I had built out my models with validates like the instructions state.

Thanks for considering this feedback!

**Comment by linda-seiter** [comment]
instructions updated
