### ISSUE TITLE
confusing instructions

### ISSUE THREAD

**Issue by Michoel-89** [learn-co-curriculum/python-p4-iam-putting-it-all-together-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/6445/assignments/245578?module_item_id=579045

### Concern

We were taught to validate columns by importing validates and then using @validates. 
This test is looking for column constraints and table constraints specifically.
The instructions are unclear it says: 
1) validate the user's username to ensure that it is present and unique (no two users can have the same username).
2) Add validations for the Recipe model:

### Suggested Changes

The instructions should specify that we need to use constraints, or the tests won't pass.
Additionally, they should say that you need to either delete the database and migrations folder if you make any changes to your constraints or make a revision each time.

**Comment by linda-seiter** [comment]
instructions updated
